Repository yezz123/authx, pull requests merged in 2021-11, with the labels that each got.

#102 Docs: Prepare Project for Being Public ✨
  .all-contributorsrc
  README.md
  docs/index.md
  mkdocs.yml
Labels: documentation, Small

#108 CI: Delete Docs Build ✨
  .github/dependabot.yml
  .github/workflows/docker.yml
  .github/workflows/docs.yml
  .github/workflows/test.yml
Labels: enhancement, Extra Small

#109 Docs: Delete a part of FAQ ✨
  docs/faq.md
Labels: Extra Small

#112 chore: Fix workflows ✨
  .github/workflows/Local.yml
  .github/workflows/build-docs.yml
  .github/workflows/docs.yml
  .github/workflows/release.yml
Labels: documentation, Small, docker

#113 chore: Rename Website name & Fix Build Issue 🚀
  .github/workflows/Local.yml
  .github/workflows/docker.yml
  mkdocs.yml
  setup.py
Labels: documentation, dependencies, Extra Small

#114 Chore: Delete `aiohttp`
  setup.py
Labels: enhancement, Extra Small

#117 WIP: Add Code owner 🖇
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: No Changes, Extra Small

#115 Chore: Fix Key Directory 🔑
  tests/key/private_key
  tests/key/public_key
  tests/utils.py
Labels: enhancement, Extra Small

#120 Configure `.pyup` ✨
  .pyup.yml
Labels: dependencies, Extra Small

#130 chore: fix dockerfile commands
  .github/workflows/docker.yml
  Makefile
Labels: Extra Small, docker

#131 Chore: change Name from `AuthX` to `authx` ✨
  .github/workflows/build-docs.yml
  .github/workflows/deploy-docs.yml
  README.md
  docs/configuration/auth/jwt.md
  docs/configuration/core/user_manager.md
  docs/configuration/models/base.md
  docs/configuration/models/social.md
  docs/configuration/routers/administration.md
  docs/configuration/routers/authentication.md
  docs/configuration/routers/index.md
  docs/configuration/routers/password.md
  docs/configuration/routers/search.md
  docs/configuration/routers/social.md
  docs/configuration/social/index.md
  docs/contributing.md
  docs/index.md
  docs/installation.md
  docs/src/main.py
  docs/src/mongo.py
  docs/src/redis.py
Labels: documentation, Medium, docker

#132 Bump version from 0.1.1 to 0.1.2 ✨
  Setup.cfg
  authx/__init__.py
Labels: Extra Small

#133 Rebase Branch
  .github/workflows/build-docs.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/docker.yml
  Makefile
  README.md
  Setup.cfg
  authx/__init__.py
  docs/configuration/auth/jwt.md
  docs/configuration/core/user_manager.md
  docs/configuration/models/base.md
  docs/configuration/models/social.md
  docs/configuration/routers/administration.md
  docs/configuration/routers/authentication.md
  docs/configuration/routers/index.md
  docs/configuration/routers/password.md
  docs/configuration/routers/search.md
  docs/configuration/routers/social.md
  docs/configuration/social/index.md
  docs/contributing.md
  docs/index.md
  docs/installation.md
  docs/release.md
  docs/src/main.py
  docs/src/mongo.py
  docs/src/redis.py
Labels: Large

#134 chore: add sameSite attribute to the http only cookie
  authx/routers/social.py
Labels: enhancement, Extra Small

#139 chore: update Requirements ✨
  requirements.dev.txt
  requirements.txt
  setup.py
Labels: dependencies, Extra Small

#140 CI: Add Code Security Analyse ✨
  .github/workflows/codeql-analysis.yml
Labels: dependencies, Extra Small

#143 chore: Add JWT Algorithm Choices ✨
  .coveragerc
  authx/core/config.py
  authx/core/jwt.py
  authx/main.py
  authx/routers/social.py
Labels: enhancement, Extra Small

#144 Docs: Add financial Supporters ✨
  .all-contributorsrc
  README.md
Labels: documentation, Extra Small

#151 Bump PyJWT version from 1.7.1 to 2.3.0
  authx/core/jwt.py
  requirements.txt
  tests/utils.py
Labels: Extra Small

#153 chore: Remove Todos assign 🖇
  authx/core/password.py
  authx/database/mongodb.py
  authx/database/redis.py
  authx/models/user.py
  authx/services/auth.py
  authx/services/password.py
  authx/utils/captcha.py
  authx/utils/strings.py
  docs/configuration/routers/social.md
  tests/routers/test_routers_auth.py
  tests/routers/test_routers_password.py
  tests/routers/test_routers_social.py
  tests/services/test_services_auth.py
  tests/services/test_services_password.py
  tests/utils.py
Labels: enhancement, Extra Small

#154 Upgrade `pre-commit` requirements ✨
  .pre-commit-config.yaml
  authx/api/users.py
  authx/core/jwt.py
  authx/core/logger.py
  authx/database/mongodb.py
  authx/main.py
  authx/models/user.py
  authx/resources/error_messages.py
  authx/routers/admin.py
  authx/routers/auth.py
  authx/services/admin.py
  authx/services/search.py
  tests/routers/test_routers_admin.py
  tests/routers/test_routers_auth.py
  tests/routers/test_routers_password.py
  tests/routers/test_routers_search.py
  tests/routers/test_routers_social.py
  tests/services/test_services_auth.py
  tests/services/test_services_password.py
Labels: Medium, dependencies

#163 chore: add FastAPI to Classifiers
  setup.py
Labels: Extra Small

#165 Chore: Fix CI & Delete Docker Configuration ✨
  .dockerignore
  .github/dependabot.yml
  .github/workflows/Local.yml
  .github/workflows/build-docs.yml
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker.yml
  .github/workflows/documentation.yml
  .pre-commit-config.yaml
  Dockerfile
  Makefile
  README.md
  docker-compose.yml
  docs/contributing.md
  docs/index.md
Labels: enhancement, Large, docker

#168 CI: Ignore some Directories 🪨
  .github/workflows/build.yml
  pytest.ini
Labels: Extra Small, python
