Repository yezz123/authx, pull requests merged in 2022-03, with the labels that each got.

#215 docs(mkdocs.yml): Change name from `middlewares` to `middleware`
  docs/configuration/middleware/example.md
  docs/configuration/middleware/index.md
  mkdocs.yml
Labels: Extra Small

#216 chore(f/l): Integrate `Pyupgrade` to AuthX Environment
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependencies, Extra Small

#217 chore(feat): Integrate HTTP Caching Model for authx ✨
  .github/workflows/test.yml
  README.md
  authx/__init__.py
  authx/cache/backend.py
  authx/core/expiry.py
  authx/core/time.py
  authx/middleware/service.py
  authx/models/cache.py
  authx/utils/keys.py
  authx/utils/logger.py
  codecov.yml
  docs/configuration/cache/Example.md
  docs/configuration/cache/HTTPCache.md
  docs/configuration/cache/index.md
  docs/help.md
  mkdocs.yml
  pyproject.toml
  scripts/test.sh
  tests/cache/__init__.py
  tests/cache/test_cache_config.py
  tests/cache/test_http_cache.py
  tests/cache/test_keys.py
  tests/cache/test_method_cache.py
  tests/utils.py
Labels: documentation, enhancement, Extra Large, dependencies, python

#222 chore(ref): Improve API and refactor users management code
  authx/__init__.py
  authx/api/users.py
  authx/backend/__init__.py
  authx/backend/api/__init__.py
  authx/backend/api/confirm.py
  authx/backend/api/crud.py
  authx/backend/api/manage.py
  authx/backend/api/password.py
  authx/backend/api/protection.py
  authx/backend/api/users.py
  authx/backend/base.py
  authx/main.py
  authx/routers/admin.py
  authx/routers/auth.py
  authx/routers/password.py
  authx/routers/search.py
  authx/routers/social.py
  authx/services/admin.py
  authx/services/auth.py
  authx/services/password.py
  authx/services/search.py
  authx/services/social.py
Labels: documentation
