Repository yezz123/authx, pull requests merged in 2024-07, with the labels that each got.

#632 ⬆ Bump `uv` version to `0.2.18`
  .github/workflows/ci.yml
Labels: upgrade

#635 ⬆️ Update pydantic and pydantic-core versions to 2.8.0 and 2.20.0
  requirements/docs.txt
  requirements/pyproject.txt
Labels: upgrade

#636 ♻️ Refactor CSRF token retrieval
  authx/core.py
  tests/internal/test_signature.py
  tests/test_core.py
Labels: internal

#638 🔧 Support both pydantic versions
  .github/workflows/ci.yml
  authx/config.py
  authx/core.py
  authx/schema.py
  authx/token.py
  pyproject.toml
  requirements/docs.txt
  requirements/pyproject.txt
  tests/test_schema.py
Labels: feature

#640 ♻️ Refactor `_CallbackHandler` to handle optional model instances
  authx/_internal/_callback.py
  authx/config.py
  pyproject.toml
  requirements/docs.txt
  requirements/linting.txt
Labels: refactor

#641 🐛 add support for additional data in JWT token creation and decoding
  authx/main.py
  authx/schema.py
  authx/token.py
  tests/extend/__init__.py
  tests/extend/test_authx_extend.py
  tests/test_authx.py
Labels: bug

#642 ⬆️ Update uv version to `0.2.24`
  .github/workflows/ci.yml
Labels: upgrade

#643 🐛 fix unsupported comparison between two type instances
  authx/main.py
  tests/test_implicit_middleware.py
Labels: bug

#646 🔧 Re-organize `mkdocs` configuration & add new plugins
  docs/development/contributing.md
  docs/extra/Cache.md
  docs/img/data/1.png
  docs/img/data/2.png
  docs/index.md
  mkdocs.yml
  requirements/docs.in
  requirements/docs.txt
  tests/internal/test_utils.py
Labels: docs

#649 📝 Update image URL in different pages & Fix naming typo
  docs/extra/Metrics.md
  docs/faq/faq.md
  docs/faq/help.md
  docs/faq/license.md
  docs/img/data/3.png
  docs/img/license.png
  docs/img/sponsor.svg
  docs/index.md
  docs/release.md
  mkdocs.yml
  requirements/docs.txt
Labels: docs

#650 ⬆️ Update uv version to `0.2.30`
  .github/workflows/ci.yml
Labels: upgrade
