Repository yezz123/authx, pull requests merged in 2024-03, with the labels that each got.

#551 👷 Add uv-version for uv action
  .github/workflows/ci.yml
Labels: github_actions

#552 Add `mkdocstrings` to mkdocs configuration
  README.md
  authx/exceptions.py
  docs/api/config.md
  docs/api/dependencies.md
  docs/api/exceptions.md
  docs/api/main.md
  docs/api/reference.md
  docs/api/request.md
  docs/api/token.md
  docs/index.md
  mkdocs.yml
  requirements/docs.in
  requirements/docs.txt
  requirements/linting.txt
  requirements/pyproject.txt
  requirements/testing.txt
Labels: documentation

#554 Bump uv version to 0.1.17
  .github/workflows/ci.yml
Labels: dependencies

#557 ♻️ refactor documentation
  README.md
  authx/_internal/_error.py
  authx/_internal/_memory.py
  authx/_internal/_signature.py
  docs/api/internal/callback.md
  docs/api/internal/errors.md
  docs/api/internal/memory.md
  docs/api/internal/signature.md
  docs/api/reference.md
  docs/development/contributing.md
  docs/faq/code_of_conduct.md
  docs/faq/faq.md
  docs/faq/license.md
  docs/favicon.png
  docs/get-started/installation.md
  docs/help/help.md
  docs/img/header.svg
  docs/img/icon.ico
  docs/img/install.gif
  docs/img/logo.png
  docs/index.md
  docs/release.md
  mkdocs.yml
Labels: documentation

#558 📝 Add guide on accessing payload data in routes
  docs/development/contributing.md
  docs/get-started/location.md
  docs/get-started/payload.md
  mkdocs.yml
  requirements/docs.txt
  requirements/linting.txt
Labels: documentation

#559 ✨ Add Documentation & Fix Linting Rules
  README.md
  docs/callbacks/token.md
  docs/callbacks/user.md
  docs/dependencies/aliases.md
  docs/dependencies/bundle.md
  docs/dependencies/dependencies.md
  docs/dependencies/injection.md
  docs/development/contributing.md
  docs/faq/help.md
  docs/get-started/refresh.md
  docs/get-started/token.md
  docs/index.md
  mkdocs.yml
  pyproject.toml
  requirements/docs.txt
  requirements/linting.txt
  requirements/pyproject.txt
  requirements/testing.txt
Labels: documentation, enhancement, Extra Large, dependencies

#561 ✨ Update social plugin configuration
  mkdocs.yml
  requirements/docs.in
  requirements/docs.txt
  requirements/pyproject.txt
Labels: bug, documentation
