Repository yezz123/authx, pull requests merged in 2024-05, with the labels that each got.

#581 👷 Add extra job to run additional tests with Redis service
  .github/workflows/ci.yml
  scripts/test_extra.sh
Labels: internal

#582 ⬆️ Update `uv` version in CI
  .github/workflows/ci.yml
Labels: dependencies, github_actions

#583 📝 Update badges and links in README
  README.md
  docs/index.md
Labels: docs

#586 🔧 Update CI workflow, by adding release process
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: github_actions

#587 🔧 Add codespell hook for spell checking
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  authx/main.py
  docs/extra/Metrics.md
  pyproject.toml
  requirements/docs.txt
  requirements/linting.in
  requirements/linting.txt
  requirements/pyproject.txt
  requirements/testing.txt
  tests/app/test_get_subject.py
  tests/utils.py
Labels: github_actions, internal

#588 🔧 Update build targets & add `hatch-fancy-pypi-readme`
  docs/release.md
  pyproject.toml
Labels: internal

#589 ♻️ Replaces use of default mutable arguments
  authx/core.py
  authx/schema.py
  authx/token.py
Labels: python, feature

#593 🔧 Separate CI of testing from Release one
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: internal

#594 🐛 remove `print()` in the release file
  .github/workflows/release.yml
Labels: refactor
