Repository yezz123/authx, pull requests merged in 2025-03, with the labels that each got.

#736 🏗️ Update CI workflow to use only Ubuntu
  .github/workflows/ci.yml
Labels: internal

#737 📝 Update documentation for AuthX
  docs/get-started/basic-usage.md
  docs/get-started/location.md
  docs/get-started/refresh.md
Labels: documentation, docs

#738 ✨ Add examples for AuthX authentication
  examples/README.md
  examples/examples/__init__.py
  examples/examples/basic_auth.py
  examples/examples/fresh_token.py
  examples/examples/refresh_token.py
  examples/examples/token_blocklist.py
  examples/examples/token_locations.py
  examples/pyproject.toml
  examples/tests/__init__.py
  examples/tests/conftest.py
  examples/tests/test_examples.py
  examples/uv.lock
  pyproject.toml
Labels: internal

#741 ♻️ Deprecate data keyword argument in `decode_token`
  authx/exceptions.py
  authx/token.py
  tests/test_token.py
Labels: feature
